
insert into product (product_name, price, img, description) values ('French Kiss Vanilla', 13409, 'https://robohash.org/blanditiisexaut.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Pecan Raisin - Tarts', 6961, 'https://robohash.org/dolorquialaudantium.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Beef - Baby, Liver', 21240, 'https://robohash.org/sittemporead.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Soup - French Onion, Dry', 6037, 'https://robohash.org/sapienteexpeditalaborum.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Trueblue - Blueberry 12x473ml', 8052, 'https://robohash.org/minussintcum.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Squid - U 5', 10366, 'https://robohash.org/rerumnequeut.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Marjoram - Dried, Rubbed', 19243, 'https://robohash.org/temporaexpeditaaccusantium.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Irish Cream - Butterscotch', 24134, 'https://robohash.org/veroautemsapiente.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Beer - Alexander Kieths, Pale Ale', 18202, 'https://robohash.org/idharumaspernatur.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Daves Island Stinger', 5628, 'https://robohash.org/providentdeseruntillo.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Bar Energy Chocchip', 19623, 'https://robohash.org/asperioresidtempora.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Crab - Claws, Snow 16 - 24', 7744, 'https://robohash.org/etanimidoloremque.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Butter Balls Salted', 18245, 'https://robohash.org/nihileumlabore.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Lid - High Heat, Super Clear', 24532, 'https://robohash.org/veroetarchitecto.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Appetiser - Bought', 25034, 'https://robohash.org/quisautemaut.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Curry Powder', 2735, 'https://robohash.org/delenitimaioresid.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Pastry - Cherry Danish - Mini', 5919, 'https://robohash.org/dolorummodia.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Rosemary - Fresh', 22393, 'https://robohash.org/asperioresutfuga.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Squid - U 5', 2240, 'https://robohash.org/aperiamatqueeos.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Wine - Crozes Hermitage E.', 2627, 'https://robohash.org/saepevoluptatemfacere.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Nut - Macadamia', 26903, 'https://robohash.org/praesentiumessesimilique.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Papayas', 12345, 'https://robohash.org/autoditet.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Pears - Fiorelle', 9748, 'https://robohash.org/hicquiavoluptatibus.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Honey - Lavender', 1707, 'https://robohash.org/occaecatiadipiscieius.jpg?size=50x50&set=set1', 'description');
insert into product (product_name, price, img, description) values ('Monkfish - Fresh', 15417, 'https://robohash.org/vitaealiastempore.jpg?size=50x50&set=set1', 'description');