server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/green?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: Panguk
    password: 9999
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
      file-size-threshold: 5MB

  thymeleaf:
    cache: false

  jpa:

    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        hbm2ddl:
          import_files: classpath:db/data.sql